<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Pridať inzerát';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('product', array('action' => 'add')));
 $form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('category_id'));
echo $this->formRow($form->get('phone'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('price'));
echo $this->formRow($form->get('location'));
echo $this->formRow($form->get('shipping'));
echo $this->formRow($form->get('top')); 
echo $this->formRow($form->get('fileupload'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

