<?php

$title = $category->name;
$this->headTitle($title);

?>
<h2><?php echo $title; ?></h2>
<?php 
$count = 0;
foreach($products as $product) :
if (!$count%4)
       { echo '<div class="row">';}
?>
<div class="col-md-3 col-lg-3">
    <a href="<?php echo $this->url('product',array(
                'action' => 'show', 'id' => $product->id)); ?>" class="thumbnail">
      
      <img src="<?php echo $this->basePath('img/uploads/').$product->foto1; ?>" alt="...">
      <div class="caption">
        <h3><?php echo $this->escapeHtml($product->title); ?><?php if($product->top == 'ano') { echo '<span class="label label-warning pull-right">TOP</span>'; } ?></h3>
        <p>
            <?php echo $this->escapeHtml($product->description); ?> 
        </p>
          <table>
            <tr>
              <td>Kategória:</td> <td><span class="label label-default">
            <?php  echo $category->name; ?></span></td>
            </tr>
            <tr>
              <td>Lokalita: </td><td><span class="label label-info"><?php echo $this->escapeHtml($product->location); ?></span></td>
            </tr>
            <tr>
            <td>Cena: </td><td><span class="label label-success"><?php echo $this->escapeHtml($product->price); ?></span></td>
            </tr>
        </table>      
      </div>
  </a>
  </div>

<?php
    // close row if there is 4 thumbnails in it
    if ($count%4 == 3)
        {echo '</div><div class="row">';}

    $count++;

endforeach; 

// close the row at the end if the last one wasn't full
    if ($count%4>0){
    echo '</div>';
  }
?>
   