<?php

$title = 'Nakupujem.net';
$this->headTitle($title);
?>
<p>
    <a href="<?php echo $this->url('product', array('action'=>'add')); ?>">Pridať nový inzerát</a>
</p>    

<?php foreach($products as $product) : ?>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <a href="#" class="thumbnail">
      <img src="<?php echo $this->basePath('img/placeholder.gif') ?>" alt="...">
      <div class="caption">
        <h3><?php echo $this->escapeHtml($product->title); ?></h3>
        <p>
            <?php echo $this->escapeHtml($product->description); ?>
            <br>
            <b>Price: </b> <?php echo $this->escapeHtml($product->price); ?>
        </p>
        <p>
            <b>Lokalita: </b><?php echo $this->escapeHtml($product->location); ?>
        </p>
      </div>
  </a>
  </div>
</div>






<?php //echo $this->escapeHtml($product->email); ?>

<?php endforeach; ?>
   