<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="...">
      <div class="caption">
        <h3><?php echo sprintf($this->translate('Nadpis productu') ?></h3>
        <p><?php echo sprintf($this->translate('Popis productu') ?></p>
        <p><a href="#" class="btn btn-primary" role="button"><?php echo sprintf($this->translate('Pozri &raquo;') ?></a></p>
      </div>
    </div>
  </div>
</div>


