<?php

$title = $user->username;
$this->headTitle("Užívateľ: " . $title);
?>
<p>

</p>	

	<div class="col-md-6 col-lg-6">
		<h2><?php echo $this->escapeHtml($user->email); ?></h2> 
			<h5>Meno: <?php echo $this->escapeHtml($user->first_name); echo $this->escapeHtml($user->last_name); ?></h5>
			<div class="well">
			<p>
			Telefónne číslo: <?php echo $this->escapeHtml($user->phone); ?><br />
			Email: <?php echo $this->escapeHtml($user->email); ?>
			</p>
			<p>
				<table>
					<tr>
					<td>Lokalita: </td><td><span class="label label-info"><?php echo $this->escapeHtml($user->location); ?></span></td></tr>
				</table>
			</p>
			</div>
		</div>

	<div class="col-md-6 col-lg-6">
		
	</div>


		
		
	
</div>

	<div class="col-md-6 col-lg-6">

	</div>