<?php

$title = $user->username;
$this->headTitle("Užívateľ: " . $title);
?>
<p>

</p>	

	<div class="col-md-6 col-lg-6">
		<h2><?php echo $this->escapeHtml($user->username); ?></h2> 
			<h5>Meno: <?php echo $this->escapeHtml($user->first_name); echo $this->escapeHtml($user->last_name); ?></h5>
			<div class="well">
			<p>
			Telefónne číslo: <?php echo $this->escapeHtml($user->phone); ?><br />
			Email: <?php echo $this->escapeHtml($user->email); ?>
			</p>
			<p>
				<table>
					<tr>
					<td>Lokalita: </td><td><span class="label label-info"><?php echo $this->escapeHtml($user->location); ?></span></td></tr>
				</table>
			</p>
			</div>
			<a class="btn btn-primary" href="<?php echo $this->url('user', array('action'=>'edit', 'id'=>$user->id)); ?>"><b class="glyphicon glyphicon-edit"></b>&nbsp;Edituj</a>
			<a class="btn btn-danger" href="<?php echo $this->url('user', array('action'=>'delete', 'id'=>$user->id)); ?>"><b class="glyphicon glyphicon-remove"></b>&nbsp;Zmaž</a>
		</div>


		
		
	
</div>

	<div class="col-md-6 col-lg-6">

	</div>